using System;
using System.Diagnostics;
using System.IO;
// Code mostly from https://medium.com/emoney-engineering/running-python-script-from-c-and-working-with-the-results-843e68d230e5
namespace ImportPythonEmailModules
{
    class Program
    {
        public static string pyvar;

        static void Main(string[] args)
        {
            pyvar = run_cmd("cd","");

        }

        public static string run_cmd(string cmd, string args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "C:\\Users\\jsnea\\Anaconda2\\python.exe";
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = false; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }
        }
    }
}
